### PR TITLE
Folder for 3d files and a model for a Giant Spider

### PR DESCRIPTION
**Pull request by m7600**
If it's OK with you, maybe there could be a folder for 3d source files. 

Here is the .blend file for a Giant Black Widow model that I made. Maybe it could work for a type of enemy. It has an armature and it can be posed, but I have not made the animations yet. When I do, I'll update this file.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
The folder is fine and I guess spiders could work for the interior. Do you have a pic?
I was thinking of using these orcs, since they have all the animations already (ignore the two heroes): https://opengameart.org/users/marcintokarski

It's pointless to have this repo be a dump for assorted models though. Let's focus on what we need.

**Comment by m7600** [comment]
Yeah, I think you're right. We can use OGA for hosting the assorted models. I took a look at the orcs, it's kind of hard to tell that they're orcs because the have a lot of armor... but if you want to use those, no prob. I could try to make some orcs myself, and then we would have more options for choosing.

Here's what the spider looks like

Screenshot from 2021-03-08 14-56-33

**Comment by lynxlynxlynx** [comment]
That's a great idea — hosting on OGA. That way others get to use the assets more easily and perhaps someone jumps in and provides more textures, extra animations or some other improvement.

I was thinking of the orcs just because I found them while searching for other stuff on OGA. And they could be fitting story-wise, somehow ending being trapped inside the cave. It doesn't really matter how they're named, since the demo has no real setting or expectations for what those models should _actually_ represent. So they could be random highly intelligent and well-manered creatures.

**Comment by lynxlynxlynx** [comment]
One simple todo item you could help with immediately is this:
  - [ ] create animation (standing and walking is enough): can reuse [rabbit](https://opengameart.org/content/rabbit-0) or  [rat](https://opengameart.org/content/evil-giant-rat)

Basically just about exporting the model into a small creature animation. Then I can script it to run around in the first area.

**Comment by m7600** [comment]
Ok, cool. Sure, ill work on the rabbit and the rat. The models look really good, shouldn't be too difficult to make some .bam files for them with DLTCEP. That being said, just out of curiosity, do you think there could be an alternative to .bam files in the future? If we can export the animations directly from Blender without having to use DLTCEP that would speed up the process a lot. 

About hosting the models on OGA, that could be a way to draw more attention and traffic to GemRB, yeah.

**Comment by m7600** [comment]
I'll close this pull request then, and start to work on the rabbit and rat.

**Comment by lynxlynxlynx** [comment]
1. One is enough! :) The rabbit is probably better, since those rat ears are quite enlarged.
2. The script we started adapting will make this easier (usually avoiding the need for DLTCEP). Then BAMv2 support even more, since there'll be no palette limits any more. I don't think PNG will ever be an option, since you also need the center point coordinates somewhere. Definitely something to play with and improve later.
3. BTW, I'm adding all the OGA assets used into a collection there.

**Comment by m7600** [comment]
Ok, so DLTCEP is acting up on me, it says that I can't save the .bam files because I opened them in "read only" mode. I don't know what that means in this context, never had that problem before with this great tool, but I'll do some investigation.

In the meantime, here is a .zip file with the individual frames for the rabbit animation. I ran into several difficulties while making them. The source file for this rabbit from OGA is several years old, it was made with an old version of Blender. So, a lot of things are lost when you open it with a new version (the placing of the textures, for example). I did my best to configure everything again (the nodes, etc.). Then I used the script from Flare to render the frames. I used an interval from 0 to 4, I don't know if that's enough directions, since this is a small creature and it probably doesn't need that much detail (as in, number of directions. We may be able to get away with North, south, east, west, and their pair-wise combinations, but if you think that this needs a total of 16 directions instead of 8, no problem). 

I'm posting this here instead of making a new pull request because maybe I'll have to fix some things before trying to commit. So, here's the zip file
[rabbit.zip](https://github.com/gemrb/gemrb-assets/files/6104421/rabbit.zip)

EDIT: Oh, and the original file did not have a jumping animation for the rabbit, the only animation was that it moved its head around, so I had to make that as well.

**Comment by lynxlynxlynx** [comment]
DLTCEP: I think that's a general check-box in the settings (Setup button).

Some of the animation types do support east-west mirroring and the minimum orientation count is 5. The E and W are always the same, but N and S aren't, so we actually need 5 or 9 for the full circle (mirror to 8 and 16 respectively). 5 limits the available animation types, so it's better to export in the iwd format with more orientations.

**Comment by m7600** [comment]
Lynx, when you have time, can you check this rabbit .bam that I made? The directions are ok, I think, but there's some problem with the colors. I will have to investigate why the background is not entirely pure green, and why black spots appear on some of the frames.


[rabbitwk.zip](https://github.com/gemrb/gemrb-assets/files/6105298/rabbitwk.zip)

**Comment by m7600** [comment]
Made some progress. I fixed the borders of the rabbit, and some other stuff. The transparency is correct now. But the rabbit has some artifacts (some red and blue pixels in a few parts). You wouldn't believe what I had to do to make this work. Besides using Blender, I also had to go back and forth between DLTCEP, Bam Workshop 2, and Near Infinity, each of these doing a different function. It's too many tools for one simple rabbit. 

Here's the updated .bam file
[rabbit.zip](https://github.com/gemrb/gemrb-assets/files/6105916/rabbit.zip)

**Comment by lynxlynxlynx** [comment]
Uff, thanks, that sounds pretty terrible*. I guess in future reuses of existing models, it would be good to downsample the textures into fewer colors before exporting, so there's fewer chances of their total count exceeding the palette limit.

I can edit those odd colors out in NI pretty easily, I think. The size looks perfect btw! I'll also set the center, otherwise the foot circle appears somewhere else.

* this is why I made the BAMv2 feature request pinned months ago. I'll look at it pretty much as soon as we're over with the next release.

**Comment by lynxlynxlynx** [comment]
Pushed to the subviews branch, thanks again! That's 3 more items off the todo. :)

**Comment by m7600** [comment]
Lynx I took a look at those orcs from OGA that you linked. They don't have the 3d source file, only 2D sprite sheets. And they don't have all of the orientations that we need, I think. So I made an orc model using MakeHuman and Blender, I gave it two animations, one for standing and another for walking. I couldn't center the character circle correctly, what tool do you usually use for that, DLTCEP or Near Infinity? When you have the time, please check these .bams to see if they could be used in the demo.

[orc.zip](https://github.com/gemrb/gemrb-assets/files/6159672/orc.zip)

**Comment by lynxlynxlynx** [comment]
Ah, you're quite proactive! For centering, the last time I did it was with NI — you can set the x/y for each frame. For character animations it needs to be at the foot level and probably always at the same x, so it doesn't jump around while the animation runs.

I'll link it in the overview bug to return to it once we're there. The first area needs only some audio and we're done with stage 2. Then the second area design can get underway and that of course includes NPCs, where these models could be handy.

If you have some time, please convert the rest of ZHMW1 to the new animation type. Specifically, now you can hit empty animations, as g1 isn't present ("ready"/active version of standing). The -SC one was meant for it, but it has just 5 frames and they're quite pronounced, so perhaps it's too fast, a bad idea and we should just copy g11 to it. Or maybe duplicate the frames, so the animation is slower.

**Comment by m7600** [comment]
I made a pull request for the animations. For the audio, I can't help there right now because my speakers stopped working a few months ago, I need to repair them or get new ones. But I remember that [Flare has some nice sounds,](https://github.com/flareteam/flare-game/tree/master/mods/fantasycore/music) maybe we can use those? I can ask the Flare team if they're cool with that. I know that it's an open source project, but I think it's polite to ask before using.

**Comment by lynxlynxlynx** [comment]
Thanks and don't worry about the audio, I'm on it. The area music is the simplest of the three to procure, since there's plenty of open art.

**Pull request closed without merging**
